{
 "title": "ees-edge",
 "description": "only TPS & Latency",
 "time": { "from": "2023-04-20T05:54:12.000Z", "to": "2023-04-20T06:03:17.789Z" },
 "panels": [
  {
   "title": "APIGM View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API-PROXY TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vincent_apigm_apiproxy_north_transaction_duration_seconds_count[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(vincent_apigm_apiproxy_north_transaction_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "api-proxy latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vincent_apigm_apiproxy_north_transaction_duration_seconds_sum[1m])) * 1000 / sum(rate(vincent_apigm_apiproxy_north_transaction_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "api-proxy CPU in Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"vincent-apigm-api-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}[1m])) by (pod, name)",
     "legendFormat": "Core-usage--{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"vincent-apigm-api-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}[2m]))",
     "legendFormat": "Total-Core-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"vincent-apigm-api-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) / sum(container_spec_cpu_quota{container=~\"vincent-apigm-api-proxy\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "Total-CPU-usage"
    }
   ]
  },
  {
   "title": "api-proxy MEM in Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"vincent-apigm-api-proxy.*\",container=\"vincent-apigm-api-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    }
   ]
  },
  {
   "title": "api-proxy overload ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(vincent_apigm_apiproxy_overload_unsuccessful_response_sent_ratio[1m]))>= 0 or vector(0)"
    }
   ]
  },
  {
   "title": "Test APP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Test App TPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count[1m])) by(status)",
       "legendFormat": "test-app-{{status}}"
      }
     ]
    },
    {
     "title": "Test App Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{app_kubernetes_io_name=\"vincent-uesessionbroker\", area=\"heap\"}) by (id) / 1048576",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Test APP JVM MEM commit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(jvm_memory_committed_bytes{app_kubernetes_io_name=\"vincent-uesessionbroker\"}) by (id)/1048576"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPS (QoS Received from Jmeter)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_service_requests_recv_total[1m]))by(resource,operation)",
     "legendFormat": "nbi-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_requests_recv_total[1m]))by(resource)",
     "legendFormat": "nef notify-{{resource}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_requests_recv_total[1m]))by(resource)",
     "legendFormat": "monte notify-{{resource}}"
    },
    {
     "expr": "sum(rate(gateway_service_successful_responses_sent_total[1m])) + sum(rate(vincent_nnef_sessionwithqos_successful_responses_sent_total[1m])) + sum(rate(vincent_nnef_eventexposure_successful_responses_sent_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "successful TPS (QoS Received from Jmeter)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_service_successful_responses_sent_total[1m]))by(resource,operation)",
     "legendFormat": "nbi-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_successful_responses_sent_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_successful_responses_sent_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(gateway_service_successful_responses_sent_total[1m]))+sum(rate(vincent_nnef_sessionwithqos_successful_responses_sent_total[1m]))+sum(rate(vincent_nnef_eventexposure_successful_responses_sent_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Success Ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(increase(gateway_service_successful_responses_sent_total[1m]))>= 0 or vector(0)) + (sum(increase(vincent_nnef_sessionwithqos_successful_responses_sent_total[1m]))>= 0 or vector(0)) + (sum(increase(vincent_nnef_eventexposure_successful_responses_sent_total[1m]))>= 0 or vector(0)))/((sum(increase(gateway_service_requests_recv_total[1m]))>= 0 or vector(0)) + (sum(increase(vincent_nnef_sessionwithqos_requests_recv_total[1m]))>= 0 or vector(0)) + (sum(increase(vincent_nnef_eventexposure_requests_recv_total[1m]))>= 0 or vector(0))) * 100 >= 0 or vector(0)",
     "legendFormat": "success ratio"
    }
   ]
  },
  {
   "title": "TPS (Inbound & Outbound)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_service_requests_recv_total[1m]))by(resource,operation)",
     "legendFormat": "nbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_requests_sent_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-sent-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_requests_sent_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-send-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_requests_recv_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_requests_recv_total[1m]))by(resource,operation)",
     "legendFormat": "sbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(gateway_service_requests_sent_total[1m]))by(resource,operation)",
     "legendFormat": "nbi-sent-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(gateway_service_requests_recv_total[1m])) + sum(rate(vincent_nnef_sessionwithqos_requests_recv_total[1m])) + sum(rate(vincent_nnef_eventexposure_requests_recv_total[1m]))+sum(rate(gateway_service_requests_sent_total[1m])) + sum(rate(vincent_nnef_sessionwithqos_requests_sent_total[1m])) + sum(rate(vincent_nnef_eventexposure_requests_sent_total[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  {
   "title": "Unsuccessful TPS(Inbound & Outbound)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_service_unsuccessful_responses_sent_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "nbi-sent-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_unsuccessful_responses_recv_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "sbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_unsuccessful_responses_recv_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "sbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_sessionwithqos_unsuccessful_responses_send_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "sbi-send-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(gateway_service_unsuccessful_responses_recv_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "nbi-recv-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(vincent_nnef_eventexposure_unsuccessful_responses_send_total[1m]))by(resource,operation)>= 0 or vector(0)",
     "legendFormat": "sbi-send-{{resource}}-{{operation}}"
    },
    {
     "expr": "sum(rate(gateway_service_unsuccessful_responses_sent_total[1m]))>= 0 or vector(0) + sum(rate(vincent_nnef_sessionwithqos_unsuccessful_responses_send_total[1m]))>= 0 or vector(0) + sum(rate(vincent_nnef_eventexposure_unsuccessful_responses_send_total[1m]))>= 0 or vector(0)",
     "legendFormat": "Total-send-unsuccess"
    }
   ]
  },
  {
   "title": "QoS E2E avg latency per Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(gateway_service_request_duration_seconds_sum{resource=~\"(QOS_SUB)\",status_code=~\"(200|201)\"}[1m])) by (instance) + sum(rate(vincent_nnef_sessionwithqos_request_duration_seconds_sum{resource=~\"(NEF_QOS_NOTIFY)\",status_code=\"204\"}[1m])) by (instance) + sum(rate(vincent_nnef_eventexposure_request_duration_seconds_sum{resource=~\"(NEF_MONTE_NOTIFY)\",status_code=\"204\"}[1m])) by (instance)) / (sum(rate(gateway_service_request_duration_seconds_count{resource=~\"(QOS_SUB)\",status_code=~\"(200|201)\"}[1m])) by (instance) + sum(rate(vincent_nnef_sessionwithqos_request_duration_seconds_count{resource=~\"(NEF_QOS_NOTIFY)\",status_code=\"204\"}[1m])) by (instance) +sum(rate(vincent_nnef_eventexposure_request_duration_seconds_count{resource=~\"(NEF_MONTE_NOTIFY)\",status_code=\"204\"}[1m])) by (instance) ) * 1000",
     "legendFormat": "Total-avg-{{instance}}"
    },
    {
     "expr": "(sum(rate(gateway_service_request_duration_seconds_sum{resource=~\"(QOS_SUB)\",status_code=~\"(200|201)\"}[1m])) by (instance) ) / (sum(rate(gateway_service_request_duration_seconds_count{resource=~\"(QOS_SUB)\",status_code=~\"(200|201)\"}[1m])) by (instance) ) * 1000",
     "legendFormat": "NBI-avg-{{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gateway_service_request_duration_seconds_bucket[1m])) by (le)) * 1000",
     "legendFormat": "NBI-latency-95%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vincent_nnef_sessionwithqos_request_duration_seconds_bucket[1m])) by (le)) * 1000",
     "legendFormat": "NBI-latency-95%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vincent_nnef_eventexposure_request_duration_seconds_bucket[1m])) by (le)) * 1000",
     "legendFormat": "NBI-latency-95%"
    }
   ]
  },
  {
   "title": "QoS recv TPS per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_service_requests_recv_total[1m])) by (instance) + sum(rate(vincent_nnef_sessionwithqos_requests_recv_total[1m])) by (instance) + sum(rate(vincent_nnef_eventexposure_requests_recv_total[1m])) by (instance)",
     "legendFormat": "{{instance}}-Recv-total"
    }
   ]
  },
  {
   "title": "QoS internal avg Latency(notify/sub）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_sum{status_code=\"204\"}[1m]))/sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_count{status_code=\"204\"}[1m])) * 1000",
     "legendFormat": "nef notify internal avg latency"
    },
    {
     "expr": "sum(irate(vincent_nnef_eventexposure_request_duration_seconds_sum{status_code=\"204\"}[1m]))/sum(irate(vincent_nnef_eventexposure_request_duration_seconds_count{status_code=\"204\"}[1m]))*1000",
     "legendFormat": "monte notify internal avg latency"
    },
    {
     "expr": "sum(irate(gateway_service_internal_duration_seconds_sum{resource=\"QOS_SUB\",status_code=~\"(200|201)\"}[1m]))/sum(irate(gateway_service_internal_duration_seconds_count{resource=\"QOS_SUB\",status_code=~\"(200|201)\"}[1m])) * 1000",
     "legendFormat": "sub internal avg latency"
    },
    {
     "expr": "(sum(irate(gateway_service_internal_duration_seconds_sum{resource=\"QOS_SUB\",status_code=~\"(200|201)\"}[1m]))+sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_sum{status_code=\"204\"}[1m]))+sum(irate(vincent_nnef_eventexposure_request_duration_seconds_sum{status_code=\"204\"}[1m])))/(sum(irate(gateway_service_internal_duration_seconds_count{resource=\"QOS_SUB\",status_code=~\"(200|201)\"}[1m]))+sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_count{status_code=\"204\"}[1m]))+sum(irate(vincent_nnef_eventexposure_request_duration_seconds_count{status_code=\"204\"}[1m]))) * 1000",
     "legendFormat": "total-avg"
    }
   ]
  },
  {
   "title": "QoS TPS&Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "NBI TPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gateway_service_requests_recv_total[1m]))by(resource,operation)",
       "legendFormat": "{{resource}}-{{operation}}-recv"
      },
      {
       "expr": "sum(rate(gateway_service_requests_sent_total[1m]))by(resource)",
       "legendFormat": "{{resource}}-sent"
      },
      {
       "expr": "sum(rate(gateway_service_requests_recv_total{resource=\"QOS_SUB\"}[1m])) + sum(rate(gateway_service_requests_sent_total{resource=\"QOS_NOTIFY\"}[1m]))",
       "legendFormat": "Total NBI TPS"
      }
     ]
    },
    {
     "title": "NBI Subscription Latency",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(gateway_service_request_duration_seconds_sum[1m]))by(operation) / sum(irate(gateway_service_request_duration_seconds_count[1m]))by(operation) * 1000",
       "legendFormat": "Sub-total-{{operation}}"
      },
      {
       "expr": "sum(irate(gateway_service_internal_duration_seconds_sum[1m]))by(operation) / sum(irate(gateway_service_internal_duration_seconds_count[1m]))by(operation) * 1000",
       "legendFormat": "Sub-internal-{{operation}}"
      },
      {
       "expr": "sum(irate(gateway_service_request_duration_seconds_sum[1m]))by(instance,operation) / sum(irate(gateway_service_request_duration_seconds_count[1m]))by(instance,operation) * 1000",
       "legendFormat": "Sub-{{operation}}-{{instance}}"
      },
      {
       "expr": "sum(irate(gateway_service_internal_duration_seconds_sum[1m]))by(operation,instance) / sum(irate(gateway_service_internal_duration_seconds_count[1m]))by(operation,instance) * 1000",
       "legendFormat": "Sub-internal-{{operation}}-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(gateway_service_request_duration_seconds_bucket[1m])) by (le,operation)) * 1000",
       "legendFormat": "95%-total-{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(gateway_service_internal_duration_seconds_bucket[1m])) by (le,operation)) * 1000",
       "legendFormat": "95%-internal-{{operation}}"
      }
     ]
    },
    {
     "title": "NEF-QoS Notify Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_sum[1m]))by(operation)/sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_count[1m]))by(operation) * 1000",
       "legendFormat": "internal-{{operation}}"
      },
      {
       "expr": "sum(irate(gateway_service_client_rtt_duration_seconds_sum[1m]))by(operation)/sum(irate(gateway_service_client_rtt_duration_seconds_count[1m])) by(operation)* 1000",
       "legendFormat": "External Latency-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_sum[1m]))by(operation,instance)/sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_count[1m]))by(operation,instance) * 1000",
       "legendFormat": "internal-{{operation}}-{{instance}}"
      },
      {
       "expr": "sum(irate(gateway_service_client_rtt_duration_seconds_sum[1m]))by(operation,instance)/sum(irate(gateway_service_client_rtt_duration_seconds_count[1m])) by(operation,instance)* 1000",
       "legendFormat": "External Latency-{{operation}}-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(vincent_nnef_sessionwithqos_request_duration_seconds_bucket[1m])) by (le,operation)) * 1000",
       "legendFormat": "95%-internal-{{operation}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(gateway_service_client_rtt_duration_seconds_bucket[1m])) by (le,operation)) * 1000",
       "legendFormat": "95%-external-{{operation}}"
      }
     ]
    },
    {
     "title": "MONTE Notify Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vincent_nnef_eventexposure_request_duration_seconds_sum[1m]))by(operation)/sum(irate(vincent_nnef_eventexposure_request_duration_seconds_count[1m]))by(operation) * 1000",
       "legendFormat": "internal Latency-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_eventexposure_request_duration_seconds_sum[1m]))by(operation,instance)/sum(irate(vincent_nnef_eventexposure_request_duration_seconds_count[1m]))by(operation,instance) * 1000",
       "legendFormat": "internal Latency-{{operation}}-{{instance}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(vincent_nnef_eventexposure_request_duration_seconds_bucket[1m])) by (le,operation)) * 1000",
       "legendFormat": "95%-internal Latency-{{operation}}"
      }
     ]
    },
    {
     "title": "notify recv&send TPS in pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gateway_service_client_rtt_duration_seconds_count[1m]))by(resource,instance)",
       "legendFormat": "{{instance}}-{{resource}}-sentToAF"
      },
      {
       "expr": "sum(rate(vincent_nnef_eventexposure_requests_recv_total[1m]))by(resource,instance)",
       "legendFormat": "{{instance}}-{{resource}}-recv"
      },
      {
       "expr": "sum(rate(vincent_nnef_sessionwithqos_requests_recv_total[1m]))by(resource,instance)",
       "legendFormat": "{{instance}}-{{resource}}-recv"
      }
     ]
    },
    {
     "title": "Cassandra Latency by method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(gateway_service_data_repository_invocations_seconds_sum[1m])/irate(gateway_service_data_repository_invocations_seconds_count[1m]) * 1000",
       "legendFormat": "{{method}}-{{instance}}"
      }
     ]
    },
    {
     "title": "SBI TPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_requests_recv_total[1m]))by(operation)",
       "legendFormat": "SBI-nef notify TPS -{{resource}}-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_eventexposure_requests_recv_total[1m]))by(operation)",
       "legendFormat": "SBI-monte notify TPS -{{resource}}-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_requests_sent_total[1m]))by(operation)",
       "legendFormat": "SBI-sub to nef TPS-{{resource}}-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_eventexposure_requests_sent_total[1m]))by(operation)",
       "legendFormat": "SBI-sub to monte TPS-{{resource}}-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_requests_recv_total[1m])) + sum(irate(vincent_nnef_eventexposure_requests_recv_total[1m])) + sum(irate(vincent_nnef_sessionwithqos_requests_sent_total[1m])) + sum(irate(vincent_nnef_eventexposure_requests_sent_total[1m]))",
       "legendFormat": "SBI Total TPS "
      }
     ]
    },
    {
     "title": "SBI Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_sum[1m]))by(operation)/sum(irate(vincent_nnef_sessionwithqos_request_duration_seconds_count[1m]))by(operation)",
       "legendFormat": "NEF Notify SBI latency-{{instance}}-{{operation}}"
      },
      {
       "expr": "sum(irate(vincent_nnef_eventexposure_request_duration_seconds_sum[1m]))by(operation)/sum(irate(vincent_nnef_eventexposure_request_duration_seconds_count[1m]))by(operation)",
       "legendFormat": "MONTE NEF Notify SBI Latency-{{instance}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QoS CPU & Mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QoS Pod CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gateway-service.*\", namespace=\"ees-5g-aat-off-edge-838\", container!=\"\"}[2m])) by (pod,container) ",
     "legendFormat": "CORE usage-{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gateway-service.*\", namespace=\"ees-5g-aat-off-edge-838\",container!=\"\"}[2m])) by (pod,container) / sum(container_spec_cpu_quota{container!=\"\", pod=~\"vincent-uesessionbroker.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod,container)",
     "legendFormat": "CPU usage--{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container!=\"\", pod=~\"gateway-service.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "request cpu num"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gateway-service.*\", namespace=\"ees-5g-aat-off-edge-838\", container!=\"\"}[2m]))",
     "legendFormat": "Total-Core-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"gateway-service.*\", namespace=\"ees-5g-aat-off-edge-838\",container!=\"\"}[2m])) / sum(container_spec_cpu_quota{container!=\"\", pod=~\"gateway-service.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "Total-CPU-usage"
    }
   ]
  },
  {
   "title": "QoS Pod MEM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"gateway-service.*\", namespace=\"ees-5g-aat-off-edge-838\", container!=\"\"}) by(container)",
     "legendFormat": "{{container}}-mem-working-set"
    }
   ]
  },
  {
   "title": "QoS CPU in Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"gateway-service\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod, name) ",
     "legendFormat": "Core-usage--{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"gateway-service\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod) / sum(container_spec_cpu_quota{container=~\"gateway-service\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "qos-CPU-usage--{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"gateway-service\", namespace=\"ees-5g-aat-off-edge-838\"}[2m]))",
     "legendFormat": "Total-Core-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"gateway-service\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) / sum(container_spec_cpu_quota{container=~\"gateway-service\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "qos-Total-CPU-usage"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\"gateway-service\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "request cpu num"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"logshipper\", pod=~\"gateway-service-.*\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) / sum(container_spec_cpu_quota{container=~\"logshipper\", pod=~\"gateway-service-.*\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "shipper-Total-CPU-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"logshipper\", pod=~\"gateway-service-.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod, name) ",
     "legendFormat": "shipper-Core-usage--{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\"logshipper\", pod=~\"gateway-service-.*\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "shipper-request cpu num"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"logtransformer\", pod=~\"vincent-log-transformer-.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod, name) ",
     "legendFormat": "logtransformer-Core-usage--{{pod}}"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\"logtransformer\", pod=~\"vincent-log-transformer-.*\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "logtransformer-request cpu num"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"logtransformer\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) / sum(container_spec_cpu_quota{container=~\"logtransformer\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "logtransformer-Total-CPU-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"data\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod) / sum(container_spec_cpu_quota{container=~\"data\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "search-engine-CPU-usage--{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"data\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) / sum(container_spec_cpu_quota{container=~\"data\", namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "search-engine-Total-CPU-usage"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\"data\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod)",
     "legendFormat": "search-engine-request cpu num"
    }
   ]
  },
  {
   "title": "QoS MEM in Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"gateway-service.*\",container=\"gateway-service\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"gateway-service.*\",container=\"logshipper\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"vincent-log-transformer.*\",container=\"logtransformer\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"vincent-data-search-engine-data-.*\",container=\"data\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"gateway-service.*\",container=\"logshipper\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-working"
    }
   ]
  },
  {
   "title": "istio CPU in Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"gateway-service.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (container,pod) ",
     "legendFormat": "Core-usage--{{pod}}-{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"gateway-service.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (container,pod) / sum(container_spec_cpu_quota{container=~\"istio-proxy\", pod=~\"gateway-service.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (container,pod)",
     "legendFormat": "CPU usage--{{pod}}-{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"gateway-service.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m]))",
     "legendFormat": "Total-Core-usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"gateway-service.*\",namespace=\"ees-5g-aat-off-edge-838\"}[2m]))/ sum(container_spec_cpu_quota{container=~\"istio-proxy\", pod=~\"gateway-service.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "Total-CPU-usage"
    },
    {
     "expr": "sum(container_spec_cpu_quota{container=~\"istio-proxy\", pod=~\"gateway-service.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000)",
     "legendFormat": "request cpu num"
    }
   ]
  },
  {
   "title": "istio MEM in Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"gateway-service.*\",container=\"istio-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
     "legendFormat": "{{pod}}-{{container}}-mem-usage"
    }
   ]
  },
  {
   "title": "Overload Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overload TPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_SUB\"}[1m])) by (instance) + sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_QUERY\"}[1m])) by (instance)+ sum(rate(vincent_sbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"EVENT_REPORT\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}-overload"
      },
      {
       "expr": "sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_SUB\"}[1m])) + sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_QUERY\"}[1m])) + sum(rate(vincent_sbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"EVENT_REPORT\"}[1m]))",
       "legendFormat": "Total overload"
      }
     ]
    },
    {
     "title": "Overload Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "((sum(increase(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\"}[1m]))>= 0 or vector(0)) + (sum(increase(vincent_sbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\"}[1m])))>= 0 or vector(0))/((sum(increase(vincent_nbi_uesessionbroker_requests_recv_total[1m]))>= 0 or vector(0)) + (sum(increase(vincent_sbi_uesessionbroker_requests_recv_total{resource=\"EVENT_REPORT\"}[1m]))>= 0 or vector(0))) * 100 <= 100 or vector(0)",
       "legendFormat": "overload ratio"
      }
     ]
    },
    {
     "title": "[Total Received TPS] vs [Total Overload TPS]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vincent_sbi_uesessionbroker_requests_recv_total{resource=\"EVENT_REPORT\"}[1m])) + sum(rate(vincent_nbi_uesessionbroker_requests_recv_total{resource=\"UEINFO_QUERY\"}[1m])) + sum(rate(vincent_nbi_uesessionbroker_requests_recv_total{resource=\"UEINFO_SUB\"}[1m]))",
       "legendFormat": "Total Received TPS"
      },
      {
       "expr": "sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_SUB\"}[1m])) + sum(rate(vincent_nbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"UEINFO_QUERY\"}[1m])) + sum(rate(vincent_sbi_uesessionbroker_unsuccessful_responses_sent_total{detailed_info=\"NF_CONGESTION\", resource=\"EVENT_REPORT\"}[1m]))",
       "legendFormat": "Total Overload TPS"
      },
      {
       "expr": "sum(rate(vincent_nbi_uesessionbroker_request_duration_seconds_count{resource=~\"(UEINFO_QUERY|UEINFO_SUB)\",status_code=~\"(200|201)\"}[1m])) + sum(rate(vincent_sbi_uesessionbroker_request_duration_seconds_count{resource=~\"(EVENT_REPORT)\",status_code=\"204\"}[1m]))",
       "legendFormat": "Total successful TPS"
      }
     ]
    },
    {
     "title": "Overload TPS by type (concurrent request or queue)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vincent_nbi_uesessionbroker_requests_overload_reject_total[1m])) by (type) ",
       "legendFormat": "{{type}}-overload"
      },
      {
       "expr": "sum(rate(vincent_uesessionbroker_requests_overload_reject[1m])) ",
       "legendFormat": "channel-overload"
      }
     ]
    }
   ]
  },
  {
   "title": "Istio CPU & Mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "istio CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", namespace=\"ees-5g-aat-off-edge-838\", pod=~\"vincent-ingressgw-nef-sbi-traffic.*\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", namespace=\"ees-5g-aat-off-edge-838\", pod=~\"vincent-ingressgw-nef-nbi-trust-traffic.*\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\", namespace=\"ees-5g-aat-off-edge-838\", pod=~\"vincent-apigm-api-proxy.*\"}[1m])) by(pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Istio MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"istio-proxy\", namespace=\"ees-5g-aat-off-edge-838\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DB Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cassandra CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"cassandra\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod, container)",
       "legendFormat": "{{pod}}-{{container}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"cassandra\", namespace=\"ees-5g-aat-off-edge-838\"}[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "cassandra MEM usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"cassandra\"}",
       "legendFormat": "mem-usage-{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "cassandra MEM cache",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_cache{container=\"cassandra\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
       "legendFormat": "mem-cache-{{pod}}"
      }
     ]
    },
    {
     "title": "Cassandra operand",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_client_request_latency_seconds_count{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-.*\"}[1m]))",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Cassandra Latency ",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 97 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(cassandra_client_request_latency_seconds{quantile=\"0.99\", operation=\"write\"}) by(kubernetes_pod_name) * 1000",
       "legendFormat": "0.99-write"
      },
      {
       "expr": "avg(cassandra_client_request_latency_seconds{quantile=\"0.99\", operation=\"read\"}) by(kubernetes_pod_name) * 1000",
       "legendFormat": "0.99-read"
      }
     ]
    },
    {
     "title": "ees/oam kafka CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"messagebuskf\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ees/oam kafka MEM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container=\"messagebuskf\", namespace=\"ees-5g-aat-off-edge-838\"}) by(container,pod)",
       "legendFormat": "{{pod}}-{{container}}-mem-usage"
      }
     ]
    },
    {
     "title": "WCDB container brsc CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vincent-data-wide-column-database-cd-datacenter1-rack1.*\", container=\"brsc\", namespace=\"ees-5g-aat-off-edge-838\"}[2m])) by (pod, container)",
       "legendFormat": "{{pod}}-{{container}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"brsc\", namespace=\"ees-5g-aat-off-edge-838\"}[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Redis Ops",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vincent_redisserver_instantaneous_ops_per_sec",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cassandra block on mentable/commitlog",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "rate(cassandra_memtable_pool_allocation_latency_seconds_sum{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-.*\"}[1m])/rate(cassandra_memtable_pool_allocation_latency_seconds_count{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-.*\"}[1m]) * 1000"
      },
      {
       "expr": "rate(cassandra_commit_log_commit_latency_seconds_sum{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-.*\"}[1m])/rate(cassandra_commit_log_commit_latency_seconds_count{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-.*\"}[1m]) * 1000"
      }
     ]
    },
    {
     "title": "Redis Connection",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vincent_redisserver_connections_total[1m]))"
      }
     ]
    },
    {
     "title": "WCDB container brsc MEM usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container=\"brsc\"}",
       "legendFormat": "mem-usage-{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "cassandra_jvm_gc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "targets": [
      {
       "expr": "sum(rate(cassandra_jvm_gc_estimated_collection_duration_seconds_total{kubernetes_pod_name=~\"vincent-data-wide-column-database-cd-datacenter1-rack1-[1-9]*\", kubernetes_namespace=\"pt\"}[1m])) by (kubernetes_pod_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Simulator Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Simulator TPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vertx_http_server_requestCount_total{method=\"POST\",job=\"pt-nef-simulator\"}[1m]))by(instance)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum(rate(vertx_http_server_requestCount_total{method=\"POST\",job=\"pt-eas-simulator\"}[1m]))by(instance)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Simulator Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(vertx_http_server_responseTime_seconds_sum{method=\"POST\",job=\"pt-nef-simulator\"}[1m]) / rate(vertx_http_server_responseTime_seconds_count{method=\"POST\",job=\"pt-nef-simulator\"}[1m]) * 1000",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "rate(vertx_http_server_responseTime_seconds_sum{method=\"POST\",job=\"pt-eas-simulator\"}[1m]) / rate(vertx_http_server_responseTime_seconds_count{method=\"POST\",job=\"pt-eas-simulator\"}[1m]) * 1000",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Simulator CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"http-simulator.*\",namespace=~\"(pt-nef-simulator|pt-eas-simulator)\"}[2m])) by (pod,namespace) ",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Simulator MEM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"http-simulator.*\",namespace=~\"(pt-nef-simulator|pt-eas-simulator)\"}[2m])) by (pod,namespace) ",
       "legendFormat": "{{namespace}}-{{pod}}"
      },
      {
       "expr": "sum(rate(container_memory_working_set_bytes{pod=~\"http-simulator.*\",namespace=~\"(pt-nef-simulator|pt-eas-simulator)\"}[2m])) by (pod,namespace) ",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    },
    {
     "title": "test-sbi-traffic CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vincent-test-nef-traffic.*\",namespace=~\"(pt-nef-simulator)\"}[2m])) by (pod,namespace) ",
       "legendFormat": "{{namespace}}-{{pod}}"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vincent-cces-test-nbi-traffic.*\",namespace=~\"(pt-eas-simulator)\"}[2m])) by (pod,namespace) ",
       "legendFormat": "{{namespace}}-{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "memory_used_bytes(by area)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_used_bytes{app_kubernetes_io_name=\"gateway-service\"}) by (area, instance) / 1048576"
      }
     ]
    },
    {
     "title": "Heap_used_bytes(Eden)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_used_bytes{area=\"heap\", id=\"Eden Space\"}) by (instance) / 1048576",
       "legendFormat": "Eden Space-{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_max_bytes{app_kubernetes_io_name=\"gateway-service\"}) by (id, instance) / 1048576"
      }
     ]
    },
    {
     "title": "Heap_used_bytes(Old)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_used_bytes{app_kubernetes_io_name=\"gateway_service\", area=\"heap\", id=\"G1 Old Gen\"}) by (instance) / 1048576",
       "legendFormat": "G1-Old-{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_commit",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_committed_bytes) by (id, instance)/1048576",
       "legendFormat": "{{instance}}-{{id}}"
      }
     ]
    },
    {
     "title": "memory_usage (by id)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(gateway_service_jvm_memory_used_bytes) by (id,instance)/1048576",
       "legendFormat": "{{instance}}-{{id}}"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "increase(gateway_service_jvm_gc_pause_seconds_count[1m])",
       "legendFormat": "{{action}} {{cause}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_live_threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "gateway_service_jvm_threads_live_threads",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC pause",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "rate(gateway_service_jvm_gc_pause_seconds_sum[1m])/rate(gateway_service_jvm_gc_pause_seconds_count[1m])",
       "legendFormat": "{{action}} {{cause}} {{instance}}"
      }
     ]
    },
    {
     "title": "jvm_states_threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gateway_service_jvm_threads_states_threads",
       "legendFormat": "{{state}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PM/monitoring/",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM server CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vincent-pm-server-.*\", namespace=\"ees-5g-aat-off-edge-838\", container!=\"\"}[2m])) by (pod,container) ",
       "legendFormat": "CORE usage-{{container}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container!=\"\", pod=~\"vincent-pm-server-.*\",namespace=~\"ees-5g-aat-off-edge-838\"} / 100000) by (pod,container)",
       "legendFormat": "request cpu num {{container}}"
      }
     ]
    },
    {
     "title": "PM server MEM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"vincent-pm-server-.*\", namespace=\"ees-5g-aat-off-edge-838\", container!=\"\"}) by(container)",
       "legendFormat": "{{container}}-mem-working-set"
      }
     ]
    },
    {
     "title": "vincent-victoria-metrics-cluster-vmselect CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"vincent-victoria-metrics-cluster-vmselect.*\", namespace=\"monitoring\", container!=\"\"}[2m])) by (pod,container) ",
       "legendFormat": "CORE usage-{{pod}}-{{container}}"
      },
      {
       "expr": "sum(container_spec_cpu_quota{container!=\"\", pod=~\"vincent-victoria-metrics-cluster-vmselect.*\",namespace=~\"monitoring\"} / 100000) by (pod,container)",
       "legendFormat": "request cpu num {{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "vincent-victoria-metrics-cluster-vmselect MEM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{pod=~\"vincent-victoria-metrics-cluster-vmselect.*\", namespace=\"monitoring\", container!=\"\"}) by(pod,container)",
       "legendFormat": "{{pod}}-{{container}}-mem-working-set"
      }
     ]
    }
   ]
  }
 ]
}